services:  

  app:
    image: laravel:latest
    container_name: app
    build:
      context: ./
    networks:
      - saev_network
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data
      - .:/var/www/html
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: gileduardo/mysql:v1
    container_name: saev_mysql
    ports:
      - "3306:3306"
    environment:
      - DB_PORT=3306
      - DB_DATABASE=saev
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - saev_network
    volumes:
      - saev_mysql-data:/var/lib/saev_mysql/data
    

  mongodb:
    image: mongo:latest
    container_name: saev_mongodb
    env_file:
      - .env
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
      - saev_network

networks:
  saev_network:
    driver: bridge

volumes:
  app-data:
  saev_mysql-data:
  mongodb-data:
