services:
  server:
    image: nginx:latest
    ports:
      - "8000:8000"
    networks:
      - saev_network

  app:
    image: my-app:latest
    build:
      context: ./app
    networks:
      - saev_network
    volumes:
      - app-data:/app/data

  database:
    image: gileduardo/mysql:v1
    env_file:
      - .env
    networks:
      - saev_network
    volumes:
      - db-data:/var/lib/mysql/data

networks:
  saev_network:
    driver: bridge

volumes:
  app-data:
  db-data:
