services:
  server:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    networks:
      - saev_network
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    build:
      context: ./
    networks:
      - saev_network
    volumes:
      - app-data:/app/data
      - .:/app/src
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: gileduardo/mysql:v1
    container_name: saev_mysql
    env_file:
      - .env
    networks:
      - saev_network
    volumes:
      - saev_mysql-data:/var/lib/saev_mysql/data

  mongodb:
    image: mongo:latest
    container_name: saev_mongodb
    env_file:
      - .env
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
      - saev_network

networks:
  saev_network:
    driver: bridge

volumes:
  app-data:
  saev_mysql-data:
  mongodb-data:
